MaximilianoCalahorra/grupo-7-OO2-2024

- src/main/java/com/unla/grupo7/controllers/HomeController.java
- src/main/java/com/unla/grupo7/controllers/UserController.java
- src/main/java/com/unla/grupo7/helpers/ViewRouteHelper.java
- src/main/resources/static/css/index.css
- src/main/resources/static/css/login.css
- src/main/resources/static/css/stores.css
- Modificando Controllers
- Subiendo Htmls
- Subiendo Css
- Modificando ViewRouteHelper
> Mergeando a rama main

- src/main/java/com/unla/grupo7/TestBCryptPasswordEncoder.java
- src/main/java/com/unla/grupo7/controllers/HomeController.java
- src/main/java/com/unla/grupo7/controllers/UserController.java
- src/main/java/com/unla/grupo7/helpers/ViewRouteHelper.java
- src/main/resources/templates/home/index.html
- src/main/resources/templates/home/products.html
- src/main/resources/templates/home/stores.html
- src/main/resources/templates/user/login.html
Cambios realizados:
- Creamos vista de "products" para poder desplegar los productos almacenados en la BD.
- Creamos la ruta que lleva a la vista de "products" en el ViewHelper.
- Creamos funcion para retornar la vista "products" en el "HomeController"
- Pulimos realizando pequeños cambios en algunos archivos.
> Realizamos cambios en el proyecto.

- src/main/java/com/unla/grupo7/entities/Lot.java
- src/main/java/com/unla/grupo7/entities/Product.java
- src/main/java/com/unla/grupo7/entities/Purchase.java
- src/main/java/com/unla/grupo7/entities/Stock.java
- src/main/java/com/unla/grupo7/entities/SupplyOrder.java
Se agregan las siguientes entidades:
- SupplyOrder
- Purchase
- Product
- Stock
- Lot
Cada entidad tiene especificada los atributos necesarios de la lógica de negocio, con sus respectivos constructores  y las relaciones que pueden ser: One to one; Many to one; One to many.
> Subiendo Entities

- src/main/java/com/unla/grupo7/repositories/ILotRepository.java
- src/main/java/com/unla/grupo7/repositories/IProductRepository.java
- src/main/java/com/unla/grupo7/repositories/IPurchaseRepository.java
- src/main/java/com/unla/grupo7/repositories/IStockRepository.java
- src/main/java/com/unla/grupo7/repositories/ISupplyOrderRepository.java
En este commit, incluyo los archivos que conforman el paquete **com.unla.grupo7.repositories**. 
Estos son:
- ILotRepository.java
- IProductRepository.java
- IPurchaseRepository.java
- IStockRepository.java
- ISupplyOrderRepository.java
En ellos se definen los métodos necesarios para realizar las queries a la base de datos de la aplicación.
> Subiendo los repositories

- src/main/java/com/unla/grupo7/repositories/ILotRepository.java
- src/main/java/com/unla/grupo7/repositories/IPurchaseRepository.java
- src/main/java/com/unla/grupo7/repositories/ISupplyOrderRepository.java
Realizamos correcciones en algunas queries sobre fechas y comparaciones numéricas de:
- ILotRepository.java
- IPurchaseRepository.java
- ISupplyOrderRepository.java
> Correcciones sobre algunos repositories

- src/main/java/com/unla/grupo7/entities/Lot.java
- src/main/java/com/unla/grupo7/repositories/ILotRepository.java
- src/main/java/com/unla/grupo7/repositories/IProductRepository.java
- src/main/java/com/unla/grupo7/repositories/IPurchaseRepository.java
- src/main/java/com/unla/grupo7/repositories/IStockRepository.java
- src/main/java/com/unla/grupo7/repositories/ISupplyOrderRepository.java
- src/main/java/com/unla/grupo7/services/ILotService.java
- src/main/java/com/unla/grupo7/services/IProductService.java
- src/main/java/com/unla/grupo7/services/IPurchaseService.java
- src/main/java/com/unla/grupo7/services/IStockService.java
- src/main/java/com/unla/grupo7/services/ISupplyOrderService.java
- src/main/java/com/unla/grupo7/services/implementation/PurchaseService.java
- src/main/java/com/unla/grupo7/services/implementation/SupplyOrderService.java
Correcciones y cambios realizados:
- Se realizan correcciones sobre las clase de los paquetes Repositoy y Services.: Se quita la etiqueta "OPTIONAL" en cada una de sus clases, debido una decisión tomada por el equipo de trabajo. 
- Se agregan los services de implementación SupplyOrderService y PurchaseService.
> Correciones e implementaciones

- src/main/java/com/unla/grupo7/repositories/IProductRepository.java
- src/main/java/com/unla/grupo7/services/IProductService.java
- src/main/java/com/unla/grupo7/services/implementation/ProductService.java
Realizamos algunas correcciones sobre IProductRepository y IProductService.
Además. implementamos los métodos de IProductService en ProductService.
> Subiendo repository y service de Product

- src/main/java/com/unla/grupo7/controllers/ProductController.java
- src/main/java/com/unla/grupo7/services/IProductService.java
- src/main/java/com/unla/grupo7/services/implementation/ProductService.java
En este commit, adjuntamos modificaciones en IProductService y ProductService y correcciones en ProductController.
> Modificaciones en services y correcciones en ProductControler

- src/main/java/com/unla/grupo7/entities/Lot.java
- src/main/java/com/unla/grupo7/entities/SupplyOrder.java
Se modificó el diagrama de clases y sus respectivas relaciones. Se deberá eliminar la tabla "Lot" de la base de datos o su defecto la bd completa.
> Corrección de entities.

- src/main/java/com/unla/grupo7/entities/Stock.java
- src/main/java/com/unla/grupo7/repositories/ILotRepository.java
- src/main/java/com/unla/grupo7/services/ILotService.java
- src/main/java/com/unla/grupo7/services/IStockService.java
- src/main/java/com/unla/grupo7/services/implementation/LotService.java
- src/main/java/com/unla/grupo7/services/implementation/StockService.java
En este commit realizamos las siguientes cuestiones:
- En la entity Stock se elimina el Set de Lot.
- En StockService agregamos dos métodos:
- Uno que permite calcular la cantidad de productos del tipo que tiene el stock acumulando la cantidad de cada lote.
- Otro que permite verificar si hay el stock suficiente que solicita una compra, realizar las bajas en en cada lote de donde se obtuvo cantidad y actualizar la baja del stock en general.
- En LotService se implementa un método para traer el listado de todos los Lot que tengan determinado Stock.
> Cambios e implementaciones relacionados al stock

- src/main/java/com/unla/grupo7/entities/Lot.java
- src/main/java/com/unla/grupo7/services/ILotService.java
- src/main/java/com/unla/grupo7/services/implementation/LotService.java
Funcionalidad para eliminar lotes vacíos.
> Desarrollo del remove en LotService y ILotService

- src/main/java/com/unla/grupo7/services/ILotService.java
- src/main/java/com/unla/grupo7/services/implementation/LotService.java
Eliminando inserts redundantes
> Eliminando insert

- src/main/java/com/unla/grupo7/services/implementation/LotService.java
- src/main/java/com/unla/grupo7/services/implementation/StockService.java
Agregamos la notation de Service con un nombre para StockService y LotService.
> Corrigiendo implementación de services

- src/main/resources/templates/products/products.html
Alerta de confirmación al eliminar producto. Se considera necesario al ser un dato sensible.
> Alerta para eliminar producto

- src/main/java/com/unla/grupo7/controllers/SupplyOrderController.java
- src/main/java/com/unla/grupo7/helpers/ViewRouteHelper.java
Se agrega:
-SupplyOrderController preliminar 
-Rutas utlizadas
> Se agrega el controller y sus rutas

- src/main/java/com/unla/grupo7/controllers/SupplyOrderController.java
- src/main/java/com/unla/grupo7/entities/SupplyOrder.java
- src/main/java/com/unla/grupo7/helpers/ViewRouteHelper.java
- src/main/resources/templates/supplyOrders/supplyOrderAdd.html
- src/main/resources/templates/supplyOrders/supplyOrderSave.html
Se modifica:
-Controller
-Helper
Se agregar:
-Templates
> Se realiza lógica de supplyOrder

- src/main/resources/templates/navBar/navBarAdmin.html
> fixeando navBar

- src/main/java/com/unla/grupo7/services/implementation/LotService.java
- src/main/java/com/unla/grupo7/services/implementation/StockService.java
Limpiamos el código en 'LotService' y 'StockService' después de realizar unas pruebas que nos permitieron corregir un error con respecto a la funcionalidad de verificar el stock al momento de intentar realizar una compra.
> Limpiando el código

- src/main/java/com/unla/grupo7/controllers/SupplyOrderController.java
- src/main/java/com/unla/grupo7/repositories/IPurchaseRepository.java
- src/main/java/com/unla/grupo7/repositories/ISupplyOrderRepository.java
- src/main/resources/templates/supplyOrders/supplyOrders.html
En este commit realizamos las siguientes tareas:
- Modificación de repositories para solucionar errores en las queries.
- Vista de SupplyOrder.
- Desarrollo y corrección del SupplyOrderController.
> Más desarrollo

- src/main/java/com/unla/grupo7/controllers/PurchaseController.java
- src/main/java/com/unla/grupo7/services/implementation/StockService.java
- src/main/resources/static/css/postPurchase.css
- src/main/resources/static/css/purchaseForm.css
- src/main/resources/templates/purchases/postPurchase.html
- src/main/resources/templates/purchases/purchaseForm.html
- purchaseForm
- postPurchase
- vistas
- errores en stock
> Implementando purchase y postPurchase, corrigiendo errores y vistas.

- src/main/resources/templates/home/hello.html
- src/main/resources/templates/products/productAdd.html
- src/main/resources/templates/products/productEdit.html
- src/main/resources/templates/products/productRemove.html
- src/main/resources/templates/supplyOrders/supplyOrderAdd.html
Se agregan validaciones frontend en los input de tipo number y modificamos el tipo de algunos inputs.
> Modificaciones en las vistas

- src/main/java/com/unla/grupo7/controllers/LotController.java
- src/main/java/com/unla/grupo7/controllers/PurchaseController.java
- src/main/java/com/unla/grupo7/helpers/ViewRouteHelper.java
- src/main/java/com/unla/grupo7/repositories/ILotRepository.java
- src/main/java/com/unla/grupo7/repositories/IPurchaseRepository.java
- src/main/java/com/unla/grupo7/repositories/ISupplyOrderRepository.java
- src/main/java/com/unla/grupo7/services/ILotService.java
- src/main/java/com/unla/grupo7/services/IPurchaseService.java
- src/main/java/com/unla/grupo7/services/ISupplyOrderService.java
- src/main/java/com/unla/grupo7/services/implementation/LotService.java
- src/main/java/com/unla/grupo7/services/implementation/PurchaseService.java
- src/main/java/com/unla/grupo7/services/implementation/SupplyOrderService.java
- src/main/resources/static/css/index.css
- src/main/resources/templates/home/adminIndex.html
- src/main/resources/templates/lot/lots.html
- src/main/resources/templates/navBar/navBarAdmin.html
- src/main/resources/templates/purchases/purchases.html
- src/main/resources/templates/supplyOrders/supplyOrders.html
- Agregamos el flujo de datos para presentar las compras
- Agregamos el flujo de datos para presentar los lotes
- Implementamos  nuevas Queries 
- Desarrollamos y conectamos vistas
- Agregamos funcionalidad en los controllers de Lot y Purchase
> Modificaciones e implementaciones

- mvnw.cmd
> Fixeando error de inicio
